### PR TITLE
Remove `type` argument, `symtype`, update docs

### PR DESCRIPTION
**Pull request by 0x0f0f0f**
#36

### CODE REVIEW

**Comment by 0x0f0f0f** [comment]
#37

**Comment by ChrisRackauckas** [comment]
Was there an agreement on this?

**Comment by 0x0f0f0f** [comment]
> Was there an agreement on this?

I will file a reviewable PR with the needed changes to SU

**Comment by ChrisRackauckas** [comment]
@bowenszhu you've been considering the performance semantics, what do you think of this?

**Comment by ChrisRackauckas** [comment]
Also, is this actually correct? How is the type used in the hash if it's in the metadata?

**Comment by bowenszhu** [comment]
> @bowenszhu you've been considering the performance semantics, what do you think of this?

This seems to be merely an update on the interface, and does not bother with performance.

**Comment by bowenszhu** [comment]
> @bowenszhu you've been considering the performance semantics, what do you think of this?

This doesn't bother with performance.

> Also, is this actually correct? How is the type used in the hash if it's in the metadata?

Probably fine. In SymbolicUtils.jl, `symtype` is a part of parametrized `typeof`.

```
using SymbolicUtils

@syms x y::Complex{Int64} z::Float32

tx = typeof(x)                        # SymbolicUtils.BasicSymbolic{Number}
sx = SymbolicUtils.symtype(x)         # Number
ty = typeof(y)                        # SymbolicUtils.BasicSymbolic{Complex{Int64}}
sy = SymbolicUtils.symtype(y)         # Complex{Int64}
tz = typeof(z)                        # SymbolicUtils.BasicSymbolic{Float32}
sz = SymbolicUtils.symtype(z)         # Float32
```

**Comment by ChrisRackauckas** [comment]
If that's the case then it should just use:

```julia
@assume_effects :total __parameterless_type(T)=Base.typename(T).wrapper
parameterless_type(x) = parameterless_type(typeof(x))
parameterless_type(x::Type) = __parameterless_type(x)
```

**Pull request merged**
